#ifndef _PASS_2_ERRORS_H
#define _PASS_2_ERRORS_H

static const char *pass_2_errors[] = {
    "SYMBOL DECLARED BOTH AS EXTERN AND ENTRY",
    "DUPLICATE DECLARATION OF SYMBOL AS ENTRY",
    "OPERAND SYMBOL DOES NOT EXIST IN SYMBOL TABLE",
    "OPERAND STRUCT NAME DOES NOT EXIST AS STRUCT IN SYMBOL TABLE"};

#endif